export const SET_DARK_MODE="SET_DARK_MODE"
export const REMOVE_DARK_MODE = "REMOVE_DARK_MODE"

export const ADD_GROCERY_TO_SHOPPING_LIST = "ADD_GROCERY_TO_SHOPPING_LIST";
export const REMOVE_GROCERY_FROM_SHOPPING_LIST = "REMOVE_GROCERY_FROM_SHOPPING_LIST";
export const ADD_GROCERY_TO_SHOPPING_LIST_ERR = "ADD_GROCERY_TO_SHOPPING_LIST_ERR";