export const SET_DARK_MODE = "SET_DARK_MODE"
export const REMOVE_DARK_MODE = "REMOVE_DARK_MODE"
//SHOPPING
export const ADD_SHOPPING_LIST = "ADD_SHOPPING_LIST";
export const ADD_SHOPPING_LIST_ERR = "ADD_SHOPPING_LIST_ERR";
export const ADD_GROCERY_TO_SHOPPING_LIST = "ADD_GROCERY_TO_SHOPPING_LIST";
export const REMOVE_GROCERY_FROM_SHOPPING_LIST = "REMOVE_GROCERY_FROM_SHOPPING_LIST";
export const ADD_GROCERY_TO_SHOPPING_LIST_ERR = "ADD_GROCERY_TO_SHOPPING_LIST_ERR";
//INVENTORY
export const ADD_GROCERY_TO_INVENTORY_LIST = "ADD_GROCERY_TO_INVENTORY_LIST";
export const REMOVE_GROCERY_FROM_INVENTORY_LIST = "REMOVE_GROCERY_FROM_INVENTORY_LIST";
export const ADD_GROCERY_TO_INVENTORY_LIST_ERR = "ADD_GROCERY_TO_INVENTORY_LIST_ERR";

// USER AUTH / REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERR = "AUTH_ERR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";